// Code generated by goctl. DO NOT EDIT!
// Source: activitie.proto

package server

import (
	"context"

	"backend/service/activities/cmd/rpc/internal/logic"
	"backend/service/activities/cmd/rpc/internal/svc"
	"backend/service/activities/cmd/rpc/pb"
)

type ActivitysrvServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedActivitysrvServer
}

func NewActivitysrvServer(svcCtx *svc.ServiceContext) *ActivitysrvServer {
	return &ActivitysrvServer{
		svcCtx: svcCtx,
	}
}

// -----------------------活动信息表-----------------------
func (s *ActivitysrvServer) AddActivities(ctx context.Context, in *pb.AddActivitiesReq) (*pb.AddActivitiesResp, error) {
	l := logic.NewAddActivitiesLogic(ctx, s.svcCtx)
	return l.AddActivities(in)
}

func (s *ActivitysrvServer) UpdateActivities(ctx context.Context, in *pb.UpdateActivitiesReq) (*pb.UpdateActivitiesResp, error) {
	l := logic.NewUpdateActivitiesLogic(ctx, s.svcCtx)
	return l.UpdateActivities(in)
}

func (s *ActivitysrvServer) DelActivities(ctx context.Context, in *pb.DelActivitiesReq) (*pb.DelActivitiesResp, error) {
	l := logic.NewDelActivitiesLogic(ctx, s.svcCtx)
	return l.DelActivities(in)
}

func (s *ActivitysrvServer) DelActivitiesBatch(ctx context.Context, in *pb.DelActivitiesBatchReq) (*pb.DelActivitiesResp, error) {
	l := logic.NewDelActivitiesBatchLogic(ctx, s.svcCtx)
	return l.DelActivitiesBatch(in)
}

func (s *ActivitysrvServer) GetActivitiesById(ctx context.Context, in *pb.GetActivitiesByIdReq) (*pb.GetActivitiesByIdResp, error) {
	l := logic.NewGetActivitiesByIdLogic(ctx, s.svcCtx)
	return l.GetActivitiesById(in)
}

func (s *ActivitysrvServer) SearchActivities(ctx context.Context, in *pb.SearchActivitiesReq) (*pb.SearchActivitiesResp, error) {
	l := logic.NewSearchActivitiesLogic(ctx, s.svcCtx)
	return l.SearchActivities(in)
}
