// Code generated by goctl. DO NOT EDIT.
package types

type ActivityPostReq struct {
	Address     string `db:"address" json:"address,default="`                          // 活动地址
	Cover       string `db:"cover" json:"cover,default="`                              // 封面
	CreateBy    string `db:"create_by" json:"create_by,default="`                      // 创建者
	Description string `db:"description" json:"description,default="`                  // 简介
	Id          int64  `db:"id" json:"id,optional"`                                    // ID
	Quantity    int64  `db:"quantity" json:"quantity,default=0"`                       // 数量
	Sort        int64  `db:"sort" json:"sort,default=0"`                               // 排序
	TimeEnd     string `db:"time_end" json:"time_end,default=2006-01-02 15:04:05"`     // 结束时间
	TimeStart   string `db:"time_start" json:"time_start,default=2006-01-02 15:04:05"` // 开始时间
	Title       string `db:"title" json:"title,default="`                              // 标题
	UpdateBy    string `db:"update_by" json:"update_by,default="`                      // 更新者
}

type ActivityReply struct {
	Id   int64  `json:"id"`
	Name string `json:"name"`
}

type ActivityListReq struct {
	Page     int64  `json:"page,optional,default=1" form:"page,optional,default=1"`
	PageSize int64  `json:"pageSize,optional,default=10" form:"pageSize,optional,default=10"`
	Keyword  string `json:"keyword,optional" form:"pageSize,optional"`
}

type ActivityDelReq struct {
	Id int64 `json:"id"`
}

type ActivityDelBatchReq struct {
	Ids string `json:"ids"`
}
