// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	activityOrdersFieldNames          = builder.RawFieldNames(&ActivityOrders{})
	activityOrdersRows                = strings.Join(activityOrdersFieldNames, ",")
	activityOrdersRowsExpectAutoSet   = strings.Join(stringx.Remove(activityOrdersFieldNames, "`id`", "`created_at`", "`deleted_at`", "`updated_at`"), ",")
	activityOrdersRowsWithPlaceHolder = strings.Join(stringx.Remove(activityOrdersFieldNames, "`id`", "`created_at`", "`deleted_at`", "`updated_at`"), "=?,") + "=?"

	cacheDbZeromicroActivityOrdersIdPrefix = "cache:dbZeromicro:activityOrders:id:"
)

type (
	activityOrdersModel interface {
		Insert(ctx context.Context, data *ActivityOrders) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*ActivityOrders, error)
		FindOneByName(ctx context.Context, keyword string) (*ActivityOrders, error)
		List(ctx context.Context, page, pageSize int64, keyword string) ([]*ActivityOrders, int64, error)
		Update(ctx context.Context, data *ActivityOrders) error
		Delete(ctx context.Context, id int64) error
		DeleteBatch(ctx context.Context, ids string) error
	}

	defaultActivityOrdersModel struct {
		sqlc.CachedConn
		table string
	}

	ActivityOrders struct {
		Id         int64     `db:"id"`          // ID
		MemberId   int64     `db:"member_id"`   // 用户ID
		ActivityId int64     `db:"activity_id"` // 活动ID
		Status     int64     `db:"status"`      // 0报名1签到2取消3超时失约
		SeatNumber int64     `db:"seat_number"` // 座位
		CreatedAt  time.Time `db:"created_at"`  // 创建时间(借书日期)
		UpdatedAt  time.Time `db:"updated_at"`  // 更新时间
		DeletedAt  time.Time `db:"deleted_at"`  // 删除时间
	}
)

func newActivityOrdersModel(conn sqlx.SqlConn, c cache.CacheConf) *defaultActivityOrdersModel {
	return &defaultActivityOrdersModel{
		CachedConn: sqlc.NewConn(conn, c),
		table:      "`activity_orders`",
	}
}

func (m *defaultActivityOrdersModel) Delete(ctx context.Context, id int64) error {
	dbZeromicroActivityOrdersIdKey := fmt.Sprintf("%s%v", cacheDbZeromicroActivityOrdersIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set `deleted_at`=? where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, time.Now().Format("2006-01-02 15:04:05"), id)
	}, dbZeromicroActivityOrdersIdKey)
	return err
}

func (m *defaultActivityOrdersModel) DeleteBatch(ctx context.Context, ids string) error {
	query := fmt.Sprintf("update %s set `deleted_at`=? where `id` in (%s)", m.table, ids)
	_, err := m.ExecNoCacheCtx(ctx, query, time.Now().Format("2006-01-02 15:04:05"))
	// 删除缓存
	idArr := strings.Split(ids, ",")
	for _, id := range idArr {
		dbZeromicroIdKey := fmt.Sprintf("%s%v", cacheDbZeromicroActivityOrdersIdPrefix, id)
		m.DelCache(dbZeromicroIdKey)
	}

	return err
}
func (m *defaultActivityOrdersModel) FindOne(ctx context.Context, id int64) (*ActivityOrders, error) {
	dbZeromicroActivityOrdersIdKey := fmt.Sprintf("%s%v", cacheDbZeromicroActivityOrdersIdPrefix, id)
	var resp ActivityOrders
	err := m.QueryRowCtx(ctx, &resp, dbZeromicroActivityOrdersIdKey, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", activityOrdersRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultActivityOrdersModel) FindOneByName(ctx context.Context, keyword string) (*ActivityOrders, error) {
	var resp ActivityOrders
	query := fmt.Sprintf("select %s from %s where %s and `name` = ? limit 1", activityOrdersRows, m.table, "`deleted_at`='2006-01-02 15:04:05'")
	err := m.CachedConn.QueryRowNoCacheCtx(ctx, &resp, query, keyword)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultActivityOrdersModel) List(ctx context.Context, page, pageSize int64, keyword string) ([]*ActivityOrders, int64, error) {
	var total int64
	// 条件处理
	whereCondition := "where `deleted_at`='2006-01-02 15:04:05'"
	if keyword != "" {
		whereCondition += "and `name` like '%" + keyword + "%'"
	}
	orderBy := "order by id asc"

	items := make([]*ActivityOrders, 0)
	query := fmt.Sprintf("SELECT %s FROM %s %s %s LIMIT ? OFFSET ?", activityOrdersRows, m.table, whereCondition, orderBy)
	queryCount := fmt.Sprintf("SELECT count(1) FROM %s %s", m.table, whereCondition)

	err := m.CachedConn.QueryRowNoCacheCtx(ctx, &total, queryCount)
	// 查询错误
	if err != nil {
		return items, total, err
	}

	// 没有记录
	if total == 0 {
		return items, total, nil
	}

	//获取记录
	if page < 1 {
		page = 1
	}
	err = m.CachedConn.QueryRowsNoCache(&items, query, pageSize, pageSize*(page-1))
	if err != nil {
		if err == sqlx.ErrNotFound {
			return nil, total, ErrNotFound
		}
		return nil, total, err
	}

	return items, total, nil
}

func (m *defaultActivityOrdersModel) Insert(ctx context.Context, data *ActivityOrders) (sql.Result, error) {
	dbZeromicroActivityOrdersIdKey := fmt.Sprintf("%s%v", cacheDbZeromicroActivityOrdersIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?)", m.table, activityOrdersRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.MemberId, data.ActivityId, data.Status, data.SeatNumber)
	}, dbZeromicroActivityOrdersIdKey)
	return ret, err
}

func (m *defaultActivityOrdersModel) Update(ctx context.Context, data *ActivityOrders) error {
	dbZeromicroActivityOrdersIdKey := fmt.Sprintf("%s%v", cacheDbZeromicroActivityOrdersIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, activityOrdersRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.MemberId, data.ActivityId, data.Status, data.SeatNumber, data.Id)
	}, dbZeromicroActivityOrdersIdKey)
	return err
}

func (m *defaultActivityOrdersModel) formatPrimary(primary interface{}) string {
	return fmt.Sprintf("%s%v", cacheDbZeromicroActivityOrdersIdPrefix, primary)
}

func (m *defaultActivityOrdersModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary interface{}) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", activityOrdersRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultActivityOrdersModel) tableName() string {
	return m.table
}
