// Code generated by goctl. DO NOT EDIT!
// Source: systemuserget.proto

package systemusergeter

import (
	"context"

	"backend/service/backend/cmd/rpc/systemuserget/systemuserget"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Request  = systemuserget.Request
	Response = systemuserget.Response

	Systemusergeter interface {
		GetSystemuser(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	}

	defaultSystemusergeter struct {
		cli zrpc.Client
	}
)

func NewSystemusergeter(cli zrpc.Client) Systemusergeter {
	return &defaultSystemusergeter{
		cli: cli,
	}
}

func (m *defaultSystemusergeter) GetSystemuser(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	client := systemuserget.NewSystemusergeterClient(m.cli.Conn())
	return client.GetSystemuser(ctx, in, opts...)
}
