// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.19.4
// source: activitieOrder.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

//--------------------------------活动订单表--------------------------------
type ActivityOrders struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                   //ID
	MemberId   int64 `protobuf:"varint,2,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"`       //用户ID
	ActivityId int64 `protobuf:"varint,3,opt,name=activity_id,json=activityId,proto3" json:"activity_id,omitempty"` //活动ID
	Status     int64 `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`                           //0报名1签到2取消3超时失约
	SeatNumber int64 `protobuf:"varint,5,opt,name=seat_number,json=seatNumber,proto3" json:"seat_number,omitempty"` //座位
}

func (x *ActivityOrders) Reset() {
	*x = ActivityOrders{}
	if protoimpl.UnsafeEnabled {
		mi := &file_activitieOrder_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ActivityOrders) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivityOrders) ProtoMessage() {}

func (x *ActivityOrders) ProtoReflect() protoreflect.Message {
	mi := &file_activitieOrder_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivityOrders.ProtoReflect.Descriptor instead.
func (*ActivityOrders) Descriptor() ([]byte, []int) {
	return file_activitieOrder_proto_rawDescGZIP(), []int{0}
}

func (x *ActivityOrders) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ActivityOrders) GetMemberId() int64 {
	if x != nil {
		return x.MemberId
	}
	return 0
}

func (x *ActivityOrders) GetActivityId() int64 {
	if x != nil {
		return x.ActivityId
	}
	return 0
}

func (x *ActivityOrders) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ActivityOrders) GetSeatNumber() int64 {
	if x != nil {
		return x.SeatNumber
	}
	return 0
}

type AddActivityOrdersReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MemberId   int64 `protobuf:"varint,1,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"`       //用户ID
	ActivityId int64 `protobuf:"varint,2,opt,name=activity_id,json=activityId,proto3" json:"activity_id,omitempty"` //活动ID
	Status     int64 `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`                           //0报名1签到2取消3超时失约
	SeatNumber int64 `protobuf:"varint,4,opt,name=seat_number,json=seatNumber,proto3" json:"seat_number,omitempty"` //座位
}

func (x *AddActivityOrdersReq) Reset() {
	*x = AddActivityOrdersReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_activitieOrder_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddActivityOrdersReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddActivityOrdersReq) ProtoMessage() {}

func (x *AddActivityOrdersReq) ProtoReflect() protoreflect.Message {
	mi := &file_activitieOrder_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddActivityOrdersReq.ProtoReflect.Descriptor instead.
func (*AddActivityOrdersReq) Descriptor() ([]byte, []int) {
	return file_activitieOrder_proto_rawDescGZIP(), []int{1}
}

func (x *AddActivityOrdersReq) GetMemberId() int64 {
	if x != nil {
		return x.MemberId
	}
	return 0
}

func (x *AddActivityOrdersReq) GetActivityId() int64 {
	if x != nil {
		return x.ActivityId
	}
	return 0
}

func (x *AddActivityOrdersReq) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *AddActivityOrdersReq) GetSeatNumber() int64 {
	if x != nil {
		return x.SeatNumber
	}
	return 0
}

type AddActivityOrdersResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"` //id
}

func (x *AddActivityOrdersResp) Reset() {
	*x = AddActivityOrdersResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_activitieOrder_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddActivityOrdersResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddActivityOrdersResp) ProtoMessage() {}

func (x *AddActivityOrdersResp) ProtoReflect() protoreflect.Message {
	mi := &file_activitieOrder_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddActivityOrdersResp.ProtoReflect.Descriptor instead.
func (*AddActivityOrdersResp) Descriptor() ([]byte, []int) {
	return file_activitieOrder_proto_rawDescGZIP(), []int{2}
}

func (x *AddActivityOrdersResp) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type UpdateActivityOrdersReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                   //ID
	MemberId   int64 `protobuf:"varint,2,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"`       //用户ID
	ActivityId int64 `protobuf:"varint,3,opt,name=activity_id,json=activityId,proto3" json:"activity_id,omitempty"` //活动ID
	Status     int64 `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`                           //0报名1签到2取消3超时失约
	SeatNumber int64 `protobuf:"varint,5,opt,name=seat_number,json=seatNumber,proto3" json:"seat_number,omitempty"` //座位
}

func (x *UpdateActivityOrdersReq) Reset() {
	*x = UpdateActivityOrdersReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_activitieOrder_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateActivityOrdersReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateActivityOrdersReq) ProtoMessage() {}

func (x *UpdateActivityOrdersReq) ProtoReflect() protoreflect.Message {
	mi := &file_activitieOrder_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateActivityOrdersReq.ProtoReflect.Descriptor instead.
func (*UpdateActivityOrdersReq) Descriptor() ([]byte, []int) {
	return file_activitieOrder_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateActivityOrdersReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateActivityOrdersReq) GetMemberId() int64 {
	if x != nil {
		return x.MemberId
	}
	return 0
}

func (x *UpdateActivityOrdersReq) GetActivityId() int64 {
	if x != nil {
		return x.ActivityId
	}
	return 0
}

func (x *UpdateActivityOrdersReq) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *UpdateActivityOrdersReq) GetSeatNumber() int64 {
	if x != nil {
		return x.SeatNumber
	}
	return 0
}

type UpdateActivityOrdersResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateActivityOrdersResp) Reset() {
	*x = UpdateActivityOrdersResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_activitieOrder_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateActivityOrdersResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateActivityOrdersResp) ProtoMessage() {}

func (x *UpdateActivityOrdersResp) ProtoReflect() protoreflect.Message {
	mi := &file_activitieOrder_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateActivityOrdersResp.ProtoReflect.Descriptor instead.
func (*UpdateActivityOrdersResp) Descriptor() ([]byte, []int) {
	return file_activitieOrder_proto_rawDescGZIP(), []int{4}
}

type DelActivityOrdersReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"` //id
}

func (x *DelActivityOrdersReq) Reset() {
	*x = DelActivityOrdersReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_activitieOrder_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DelActivityOrdersReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelActivityOrdersReq) ProtoMessage() {}

func (x *DelActivityOrdersReq) ProtoReflect() protoreflect.Message {
	mi := &file_activitieOrder_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelActivityOrdersReq.ProtoReflect.Descriptor instead.
func (*DelActivityOrdersReq) Descriptor() ([]byte, []int) {
	return file_activitieOrder_proto_rawDescGZIP(), []int{5}
}

func (x *DelActivityOrdersReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DelActivityOrdersBatchReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ids string `protobuf:"bytes,1,opt,name=ids,proto3" json:"ids,omitempty"` //id
}

func (x *DelActivityOrdersBatchReq) Reset() {
	*x = DelActivityOrdersBatchReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_activitieOrder_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DelActivityOrdersBatchReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelActivityOrdersBatchReq) ProtoMessage() {}

func (x *DelActivityOrdersBatchReq) ProtoReflect() protoreflect.Message {
	mi := &file_activitieOrder_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelActivityOrdersBatchReq.ProtoReflect.Descriptor instead.
func (*DelActivityOrdersBatchReq) Descriptor() ([]byte, []int) {
	return file_activitieOrder_proto_rawDescGZIP(), []int{6}
}

func (x *DelActivityOrdersBatchReq) GetIds() string {
	if x != nil {
		return x.Ids
	}
	return ""
}

type DelActivityOrdersResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DelActivityOrdersResp) Reset() {
	*x = DelActivityOrdersResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_activitieOrder_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DelActivityOrdersResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelActivityOrdersResp) ProtoMessage() {}

func (x *DelActivityOrdersResp) ProtoReflect() protoreflect.Message {
	mi := &file_activitieOrder_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelActivityOrdersResp.ProtoReflect.Descriptor instead.
func (*DelActivityOrdersResp) Descriptor() ([]byte, []int) {
	return file_activitieOrder_proto_rawDescGZIP(), []int{7}
}

type GetActivityOrdersByIdReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"` //id
}

func (x *GetActivityOrdersByIdReq) Reset() {
	*x = GetActivityOrdersByIdReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_activitieOrder_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetActivityOrdersByIdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActivityOrdersByIdReq) ProtoMessage() {}

func (x *GetActivityOrdersByIdReq) ProtoReflect() protoreflect.Message {
	mi := &file_activitieOrder_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActivityOrdersByIdReq.ProtoReflect.Descriptor instead.
func (*GetActivityOrdersByIdReq) Descriptor() ([]byte, []int) {
	return file_activitieOrder_proto_rawDescGZIP(), []int{8}
}

func (x *GetActivityOrdersByIdReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetActivityOrdersByIdResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ActivityOrders *ActivityOrders `protobuf:"bytes,1,opt,name=activity_orders,json=activityOrders,proto3" json:"activity_orders,omitempty"` //activity_orders
}

func (x *GetActivityOrdersByIdResp) Reset() {
	*x = GetActivityOrdersByIdResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_activitieOrder_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetActivityOrdersByIdResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActivityOrdersByIdResp) ProtoMessage() {}

func (x *GetActivityOrdersByIdResp) ProtoReflect() protoreflect.Message {
	mi := &file_activitieOrder_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActivityOrdersByIdResp.ProtoReflect.Descriptor instead.
func (*GetActivityOrdersByIdResp) Descriptor() ([]byte, []int) {
	return file_activitieOrder_proto_rawDescGZIP(), []int{9}
}

func (x *GetActivityOrdersByIdResp) GetActivityOrders() *ActivityOrders {
	if x != nil {
		return x.ActivityOrders
	}
	return nil
}

type SearchActivityOrdersReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page       int64 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`                               //page
	Limit      int64 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`                             //limit
	Id         int64 `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`                                   //ID
	MemberId   int64 `protobuf:"varint,4,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"`       //用户ID
	ActivityId int64 `protobuf:"varint,5,opt,name=activity_id,json=activityId,proto3" json:"activity_id,omitempty"` //活动ID
	Status     int64 `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"`                           //0报名1签到2取消3超时失约
	SeatNumber int64 `protobuf:"varint,7,opt,name=seat_number,json=seatNumber,proto3" json:"seat_number,omitempty"` //座位
}

func (x *SearchActivityOrdersReq) Reset() {
	*x = SearchActivityOrdersReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_activitieOrder_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchActivityOrdersReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchActivityOrdersReq) ProtoMessage() {}

func (x *SearchActivityOrdersReq) ProtoReflect() protoreflect.Message {
	mi := &file_activitieOrder_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchActivityOrdersReq.ProtoReflect.Descriptor instead.
func (*SearchActivityOrdersReq) Descriptor() ([]byte, []int) {
	return file_activitieOrder_proto_rawDescGZIP(), []int{10}
}

func (x *SearchActivityOrdersReq) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *SearchActivityOrdersReq) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *SearchActivityOrdersReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SearchActivityOrdersReq) GetMemberId() int64 {
	if x != nil {
		return x.MemberId
	}
	return 0
}

func (x *SearchActivityOrdersReq) GetActivityId() int64 {
	if x != nil {
		return x.ActivityId
	}
	return 0
}

func (x *SearchActivityOrdersReq) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *SearchActivityOrdersReq) GetSeatNumber() int64 {
	if x != nil {
		return x.SeatNumber
	}
	return 0
}

type SearchActivityOrdersResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ActivityOrders []*ActivityOrders `protobuf:"bytes,1,rep,name=activity_orders,json=activityOrders,proto3" json:"activity_orders,omitempty"` //activity_orders
	Total          int64             `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`                                        //记录数
}

func (x *SearchActivityOrdersResp) Reset() {
	*x = SearchActivityOrdersResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_activitieOrder_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchActivityOrdersResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchActivityOrdersResp) ProtoMessage() {}

func (x *SearchActivityOrdersResp) ProtoReflect() protoreflect.Message {
	mi := &file_activitieOrder_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchActivityOrdersResp.ProtoReflect.Descriptor instead.
func (*SearchActivityOrdersResp) Descriptor() ([]byte, []int) {
	return file_activitieOrder_proto_rawDescGZIP(), []int{11}
}

func (x *SearchActivityOrdersResp) GetActivityOrders() []*ActivityOrders {
	if x != nil {
		return x.ActivityOrders
	}
	return nil
}

func (x *SearchActivityOrdersResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_activitieOrder_proto protoreflect.FileDescriptor

var file_activitieOrder_proto_rawDesc = []byte{
	0x0a, 0x14, 0x61, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x69, 0x65, 0x4f, 0x72, 0x64, 0x65, 0x72,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x97, 0x01, 0x0a, 0x0e, 0x41,
	0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1b, 0x0a,
	0x09, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x08, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x61, 0x63,
	0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x0a, 0x61, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x65, 0x61, 0x74, 0x5f, 0x6e, 0x75, 0x6d, 0x62,
	0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x73, 0x65, 0x61, 0x74, 0x4e, 0x75,
	0x6d, 0x62, 0x65, 0x72, 0x22, 0x8d, 0x01, 0x0a, 0x14, 0x41, 0x64, 0x64, 0x41, 0x63, 0x74, 0x69,
	0x76, 0x69, 0x74, 0x79, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x12, 0x1b, 0x0a,
	0x09, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x08, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x61, 0x63,
	0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x0a, 0x61, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x65, 0x61, 0x74, 0x5f, 0x6e, 0x75, 0x6d, 0x62,
	0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x73, 0x65, 0x61, 0x74, 0x4e, 0x75,
	0x6d, 0x62, 0x65, 0x72, 0x22, 0x27, 0x0a, 0x15, 0x41, 0x64, 0x64, 0x41, 0x63, 0x74, 0x69, 0x76,
	0x69, 0x74, 0x79, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0xa0, 0x01,
	0x0a, 0x17, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79,
	0x4f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x6d, 0x65, 0x6d,
	0x62, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x6d, 0x65,
	0x6d, 0x62, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x61, 0x63, 0x74, 0x69, 0x76, 0x69,
	0x74, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x61, 0x63, 0x74,
	0x69, 0x76, 0x69, 0x74, 0x79, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x1f, 0x0a, 0x0b, 0x73, 0x65, 0x61, 0x74, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x73, 0x65, 0x61, 0x74, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72,
	0x22, 0x1a, 0x0a, 0x18, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69,
	0x74, 0x79, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x22, 0x26, 0x0a, 0x14,
	0x44, 0x65, 0x6c, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x4f, 0x72, 0x64, 0x65, 0x72,
	0x73, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x02, 0x69, 0x64, 0x22, 0x2d, 0x0a, 0x19, 0x44, 0x65, 0x6c, 0x41, 0x63, 0x74, 0x69, 0x76,
	0x69, 0x74, 0x79, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x42, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65,
	0x71, 0x12, 0x10, 0x0a, 0x03, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x69, 0x64, 0x73, 0x22, 0x17, 0x0a, 0x15, 0x44, 0x65, 0x6c, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69,
	0x74, 0x79, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x22, 0x2a, 0x0a, 0x18,
	0x47, 0x65, 0x74, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x4f, 0x72, 0x64, 0x65, 0x72,
	0x73, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x58, 0x0a, 0x19, 0x47, 0x65, 0x74, 0x41,
	0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x42, 0x79, 0x49,
	0x64, 0x52, 0x65, 0x73, 0x70, 0x12, 0x3b, 0x0a, 0x0f, 0x61, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74,
	0x79, 0x5f, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12,
	0x2e, 0x70, 0x62, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x4f, 0x72, 0x64, 0x65,
	0x72, 0x73, 0x52, 0x0e, 0x61, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x4f, 0x72, 0x64, 0x65,
	0x72, 0x73, 0x22, 0xca, 0x01, 0x0a, 0x17, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x41, 0x63, 0x74,
	0x69, 0x76, 0x69, 0x74, 0x79, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x12, 0x12,
	0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x70, 0x61,
	0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x6d, 0x65, 0x6d, 0x62,
	0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x6d, 0x65, 0x6d,
	0x62, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x61, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74,
	0x79, 0x5f, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x61, 0x63, 0x74, 0x69,
	0x76, 0x69, 0x74, 0x79, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1f,
	0x0a, 0x0b, 0x73, 0x65, 0x61, 0x74, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x0a, 0x73, 0x65, 0x61, 0x74, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x22,
	0x6d, 0x0a, 0x18, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74,
	0x79, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x12, 0x3b, 0x0a, 0x0f, 0x61,
	0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x5f, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x62, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69,
	0x74, 0x79, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x52, 0x0e, 0x61, 0x63, 0x74, 0x69, 0x76, 0x69,
	0x74, 0x79, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61,
	0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x32, 0xf7,
	0x03, 0x0a, 0x11, 0x61, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x69, 0x65, 0x4f, 0x72, 0x64, 0x65,
	0x72, 0x73, 0x76, 0x63, 0x12, 0x48, 0x0a, 0x11, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79,
	0x4f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x41, 0x64, 0x64, 0x12, 0x18, 0x2e, 0x70, 0x62, 0x2e, 0x41,
	0x64, 0x64, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x73,
	0x52, 0x65, 0x71, 0x1a, 0x19, 0x2e, 0x70, 0x62, 0x2e, 0x41, 0x64, 0x64, 0x41, 0x63, 0x74, 0x69,
	0x76, 0x69, 0x74, 0x79, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x12, 0x51,
	0x0a, 0x14, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x73,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x1b, 0x2e, 0x70, 0x62, 0x2e, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x73,
	0x52, 0x65, 0x71, 0x1a, 0x1c, 0x2e, 0x70, 0x62, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41,
	0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x48, 0x0a, 0x11, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x73, 0x44, 0x65, 0x6c, 0x12, 0x18, 0x2e, 0x70, 0x62, 0x2e, 0x44, 0x65, 0x6c, 0x41,
	0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71,
	0x1a, 0x19, 0x2e, 0x70, 0x62, 0x2e, 0x44, 0x65, 0x6c, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74,
	0x79, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x12, 0x52, 0x0a, 0x16, 0x41,
	0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x44, 0x65, 0x6c,
	0x42, 0x61, 0x74, 0x63, 0x68, 0x12, 0x1d, 0x2e, 0x70, 0x62, 0x2e, 0x44, 0x65, 0x6c, 0x41, 0x63,
	0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x42, 0x61, 0x74, 0x63,
	0x68, 0x52, 0x65, 0x71, 0x1a, 0x19, 0x2e, 0x70, 0x62, 0x2e, 0x44, 0x65, 0x6c, 0x41, 0x63, 0x74,
	0x69, 0x76, 0x69, 0x74, 0x79, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x12,
	0x54, 0x0a, 0x15, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x4f, 0x72, 0x64, 0x65, 0x72,
	0x73, 0x47, 0x65, 0x74, 0x42, 0x79, 0x49, 0x64, 0x12, 0x1c, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65,
	0x74, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x42,
	0x79, 0x49, 0x64, 0x52, 0x65, 0x71, 0x1a, 0x1d, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x41,
	0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x42, 0x79, 0x49,
	0x64, 0x52, 0x65, 0x73, 0x70, 0x12, 0x51, 0x0a, 0x14, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74,
	0x79, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x12, 0x1b, 0x2e,
	0x70, 0x62, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74,
	0x79, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x1c, 0x2e, 0x70, 0x62, 0x2e,
	0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x4f, 0x72,
	0x64, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_activitieOrder_proto_rawDescOnce sync.Once
	file_activitieOrder_proto_rawDescData = file_activitieOrder_proto_rawDesc
)

func file_activitieOrder_proto_rawDescGZIP() []byte {
	file_activitieOrder_proto_rawDescOnce.Do(func() {
		file_activitieOrder_proto_rawDescData = protoimpl.X.CompressGZIP(file_activitieOrder_proto_rawDescData)
	})
	return file_activitieOrder_proto_rawDescData
}

var file_activitieOrder_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_activitieOrder_proto_goTypes = []interface{}{
	(*ActivityOrders)(nil),            // 0: pb.ActivityOrders
	(*AddActivityOrdersReq)(nil),      // 1: pb.AddActivityOrdersReq
	(*AddActivityOrdersResp)(nil),     // 2: pb.AddActivityOrdersResp
	(*UpdateActivityOrdersReq)(nil),   // 3: pb.UpdateActivityOrdersReq
	(*UpdateActivityOrdersResp)(nil),  // 4: pb.UpdateActivityOrdersResp
	(*DelActivityOrdersReq)(nil),      // 5: pb.DelActivityOrdersReq
	(*DelActivityOrdersBatchReq)(nil), // 6: pb.DelActivityOrdersBatchReq
	(*DelActivityOrdersResp)(nil),     // 7: pb.DelActivityOrdersResp
	(*GetActivityOrdersByIdReq)(nil),  // 8: pb.GetActivityOrdersByIdReq
	(*GetActivityOrdersByIdResp)(nil), // 9: pb.GetActivityOrdersByIdResp
	(*SearchActivityOrdersReq)(nil),   // 10: pb.SearchActivityOrdersReq
	(*SearchActivityOrdersResp)(nil),  // 11: pb.SearchActivityOrdersResp
}
var file_activitieOrder_proto_depIdxs = []int32{
	0,  // 0: pb.GetActivityOrdersByIdResp.activity_orders:type_name -> pb.ActivityOrders
	0,  // 1: pb.SearchActivityOrdersResp.activity_orders:type_name -> pb.ActivityOrders
	1,  // 2: pb.activitieOrdersvc.ActivityOrdersAdd:input_type -> pb.AddActivityOrdersReq
	3,  // 3: pb.activitieOrdersvc.ActivityOrdersUpdate:input_type -> pb.UpdateActivityOrdersReq
	5,  // 4: pb.activitieOrdersvc.ActivityOrdersDel:input_type -> pb.DelActivityOrdersReq
	6,  // 5: pb.activitieOrdersvc.ActivityOrdersDelBatch:input_type -> pb.DelActivityOrdersBatchReq
	8,  // 6: pb.activitieOrdersvc.ActivityOrdersGetById:input_type -> pb.GetActivityOrdersByIdReq
	10, // 7: pb.activitieOrdersvc.ActivityOrdersSearch:input_type -> pb.SearchActivityOrdersReq
	2,  // 8: pb.activitieOrdersvc.ActivityOrdersAdd:output_type -> pb.AddActivityOrdersResp
	4,  // 9: pb.activitieOrdersvc.ActivityOrdersUpdate:output_type -> pb.UpdateActivityOrdersResp
	7,  // 10: pb.activitieOrdersvc.ActivityOrdersDel:output_type -> pb.DelActivityOrdersResp
	7,  // 11: pb.activitieOrdersvc.ActivityOrdersDelBatch:output_type -> pb.DelActivityOrdersResp
	9,  // 12: pb.activitieOrdersvc.ActivityOrdersGetById:output_type -> pb.GetActivityOrdersByIdResp
	11, // 13: pb.activitieOrdersvc.ActivityOrdersSearch:output_type -> pb.SearchActivityOrdersResp
	8,  // [8:14] is the sub-list for method output_type
	2,  // [2:8] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_activitieOrder_proto_init() }
func file_activitieOrder_proto_init() {
	if File_activitieOrder_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_activitieOrder_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ActivityOrders); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_activitieOrder_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddActivityOrdersReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_activitieOrder_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddActivityOrdersResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_activitieOrder_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateActivityOrdersReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_activitieOrder_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateActivityOrdersResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_activitieOrder_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DelActivityOrdersReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_activitieOrder_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DelActivityOrdersBatchReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_activitieOrder_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DelActivityOrdersResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_activitieOrder_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetActivityOrdersByIdReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_activitieOrder_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetActivityOrdersByIdResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_activitieOrder_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchActivityOrdersReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_activitieOrder_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchActivityOrdersResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_activitieOrder_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_activitieOrder_proto_goTypes,
		DependencyIndexes: file_activitieOrder_proto_depIdxs,
		MessageInfos:      file_activitieOrder_proto_msgTypes,
	}.Build()
	File_activitieOrder_proto = out.File
	file_activitieOrder_proto_rawDesc = nil
	file_activitieOrder_proto_goTypes = nil
	file_activitieOrder_proto_depIdxs = nil
}
