// Code generated by goctl. DO NOT EDIT.
package types

type MessageReq struct {
	Message string `db:"message" json:"message"` // json string
	Cid     string `db:"cid" json:"cid"`         // client id
}

type MessageReply struct {
	Code int64 `json:"code"`
}
