### 列表
#POST http://127.0.0.1:8892/reader/list
POST http://127.0.0.1:8893/activity/list
Content-Type: application/json
authorization: {{authorization}}

{
    "page": 1,
    "pageSize": 10
}

### 获取一个记录
POST http://127.0.0.1:8893/activity/find
Content-Type: application/json
authorization: {{authorization}}

{
  "id": 5
}


### 删除一个记录
DELETE http://127.0.0.1:8893/activity/delete
Content-Type: application/json
authorization: {{authorization}}

{
  "id": 6
}

### 删除多个记录
DELETE http://127.0.0.1:8893/activity/deleteBatch
Content-Type: application/json
authorization: {{authorization}}

{
  "ids": "6,3,4"
}

### 添加一个记录
POST http://127.0.0.1:8893/activity/add
Content-Type: application/json
authorization: {{authorization}}

{
  "title": "title",
  "address": "address",
  "time_start": 0,
  "time_end": 0,
  "description":"description",
  "quantity": 1,
  "cover": "cover",
  "sort": 1,
  "create_by": "create_by",
  "update_by": "update_by"
}

### 修改一个记录
PUT http://127.0.0.1:8893/activity/update
Content-Type: application/json
authorization: {{authorization}}

{
  "id": 5,
  "title": "titleadsfadsf10088adfadsfa",
  "address": "address",
  "time_start": 1,
  "time_end": 11,
  "description":"description",
  "quantity": 1,
  "cover": "cover",
  "sort": 1,
  "create_by": "create_by",
  "update_by": "update_by"
}


### App 列表
POST http://127.0.0.1:8893/activity/appList
Content-Type: application/json

{
  "page": 1,
  "pageSize": 10
}


### App 获取一个记录
POST http://127.0.0.1:8893/activity/appFind
Content-Type: application/json

{
  "id": 5
}