###
http://127.0.0.1:8888/admin/getUserInfo
authorization: {{authorization}}


###
POST http://127.0.0.1:8892/reader/login
Content-Type: application/json

{
    "username": "liming",
    "password": "123456"
}