http://127.0.0.1:8888/admin/getUserInfo
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NTAzOTg5NzgsImlhdCI6MTY1MDMyNjk3OCwicm9sZUlkIjo3LCJ1c2VySWQiOjF9.MZun2dqth-7Ev0LL6_xAPCCvmU7iYibma0ldoRQbY6k