// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	activity "backend/service/activities/cmd/api/internal/handler/activity"
	"backend/service/activities/cmd/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.CheckLogin},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/activity/list",
					Handler: activity.ActivityListHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/activity/delete",
					Handler: activity.ActivityDeleteHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/activity/deleteBatch",
					Handler: activity.ActivityDeleteBatchHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/activity/find",
					Handler: activity.ActivityFindOneHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/activity/add",
					Handler: activity.ActivityAddHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/activity/update",
					Handler: activity.ActivityUpdateHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)
}
