// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.4
// source: systemuserget.proto

package systemuserget

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SystemusergeterClient is the client API for Systemusergeter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SystemusergeterClient interface {
	GetSystemuser(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type systemusergeterClient struct {
	cc grpc.ClientConnInterface
}

func NewSystemusergeterClient(cc grpc.ClientConnInterface) SystemusergeterClient {
	return &systemusergeterClient{cc}
}

func (c *systemusergeterClient) GetSystemuser(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/systemuserget.Systemusergeter/getSystemuser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SystemusergeterServer is the server API for Systemusergeter service.
// All implementations must embed UnimplementedSystemusergeterServer
// for forward compatibility
type SystemusergeterServer interface {
	GetSystemuser(context.Context, *Request) (*Response, error)
	mustEmbedUnimplementedSystemusergeterServer()
}

// UnimplementedSystemusergeterServer must be embedded to have forward compatible implementations.
type UnimplementedSystemusergeterServer struct {
}

func (UnimplementedSystemusergeterServer) GetSystemuser(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSystemuser not implemented")
}
func (UnimplementedSystemusergeterServer) mustEmbedUnimplementedSystemusergeterServer() {}

// UnsafeSystemusergeterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SystemusergeterServer will
// result in compilation errors.
type UnsafeSystemusergeterServer interface {
	mustEmbedUnimplementedSystemusergeterServer()
}

func RegisterSystemusergeterServer(s grpc.ServiceRegistrar, srv SystemusergeterServer) {
	s.RegisterService(&Systemusergeter_ServiceDesc, srv)
}

func _Systemusergeter_GetSystemuser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemusergeterServer).GetSystemuser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/systemuserget.Systemusergeter/getSystemuser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemusergeterServer).GetSystemuser(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// Systemusergeter_ServiceDesc is the grpc.ServiceDesc for Systemusergeter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Systemusergeter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "systemuserget.Systemusergeter",
	HandlerType: (*SystemusergeterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "getSystemuser",
			Handler:    _Systemusergeter_GetSystemuser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "systemuserget.proto",
}
